/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Drawer: typeof import('primevue/drawer')['default']
    Menu: typeof import('primevue/menu')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
  }
}
